### ISSUE TITLE
Find a good solution to the bug

### ISSUE THREAD

**Issue by weerox** [hannes-ha/Assignment-4-manim#5]
The source of the bug is outlined in #4 and a temporary fix is available at c77c18823c7d55b7dd71b0227567e45a44e7973d. This might not be a good long-term fix. It has only been tested on a ThreeDCamera and will most likely only work with a ThreeDCamera.

Is it possible to move other cameras in other scenes? If so, how do they handle this? Should this fix include them too?

**Comment by hannes-ha** [comment]
I suggest we focus on this specific issue for this fork, and possibly expand to other areas later, to keep the PR to parent as clean as possible.

**Comment by weerox** [comment]
There's a MovingCameraScene (which use a MovingCamera) that will break using the fix in commit c77c188. I think we just have to implement the `transform_points_pre_display` method in the MovingCamera to override the default behaviour to make it work properly (this is basically how the 3D camera does it).
